/*
 * Forem API V1
 *
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ForemVersionOne.Api;
using ForemVersionOne.Model;
using ForemVersionOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ForemVersionOne.Test.Model
{
    /// <summary>
    ///  Class for testing ApiDisplayAdsGetRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiDisplayAdsGetRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiDisplayAdsGetRequest
        //private ApiDisplayAdsGetRequest instance;

        public ApiDisplayAdsGetRequestTests()
        {
            // TODO uncomment below to create an instance of ApiDisplayAdsGetRequest
            //instance = new ApiDisplayAdsGetRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiDisplayAdsGetRequest
        /// </summary>
        [Fact]
        public void ApiDisplayAdsGetRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiDisplayAdsGetRequest
            //Assert.IsType<ApiDisplayAdsGetRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'BodyMarkdown'
        /// </summary>
        [Fact]
        public void BodyMarkdownTest()
        {
            // TODO unit test for the property 'BodyMarkdown'
        }
        /// <summary>
        /// Test the property 'Approved'
        /// </summary>
        [Fact]
        public void ApprovedTest()
        {
            // TODO unit test for the property 'Approved'
        }
        /// <summary>
        /// Test the property 'Published'
        /// </summary>
        [Fact]
        public void PublishedTest()
        {
            // TODO unit test for the property 'Published'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'DisplayTo'
        /// </summary>
        [Fact]
        public void DisplayToTest()
        {
            // TODO unit test for the property 'DisplayTo'
        }
        /// <summary>
        /// Test the property 'PlacementArea'
        /// </summary>
        [Fact]
        public void PlacementAreaTest()
        {
            // TODO unit test for the property 'PlacementArea'
        }
        /// <summary>
        /// Test the property 'TagList'
        /// </summary>
        [Fact]
        public void TagListTest()
        {
            // TODO unit test for the property 'TagList'
        }

    }

}
