/*
 * Forem API V1
 *
 * Access Forem articles, users and other resources via API.         For a real-world example of Forem in action, check out [DEV](https://www.dev.to).         All endpoints can be accessed with the 'api-key' header and a accept header, but         some of them are accessible publicly without authentication.          Dates and date times, unless otherwise specified, must be in         the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ForemVersionOne.Api;
using ForemVersionOne.Model;
using ForemVersionOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ForemVersionOne.Test.Model
{
    /// <summary>
    ///  Class for testing SharedUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharedUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharedUser
        //private SharedUser instance;

        public SharedUserTests()
        {
            // TODO uncomment below to create an instance of SharedUser
            //instance = new SharedUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharedUser
        /// </summary>
        [Fact]
        public void SharedUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharedUser
            //Assert.IsType<SharedUser>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'TwitterUsername'
        /// </summary>
        [Fact]
        public void TwitterUsernameTest()
        {
            // TODO unit test for the property 'TwitterUsername'
        }
        /// <summary>
        /// Test the property 'GithubUsername'
        /// </summary>
        [Fact]
        public void GithubUsernameTest()
        {
            // TODO unit test for the property 'GithubUsername'
        }
        /// <summary>
        /// Test the property 'WebsiteUrl'
        /// </summary>
        [Fact]
        public void WebsiteUrlTest()
        {
            // TODO unit test for the property 'WebsiteUrl'
        }
        /// <summary>
        /// Test the property 'ProfileImage'
        /// </summary>
        [Fact]
        public void ProfileImageTest()
        {
            // TODO unit test for the property 'ProfileImage'
        }
        /// <summary>
        /// Test the property 'ProfileImage90'
        /// </summary>
        [Fact]
        public void ProfileImage90Test()
        {
            // TODO unit test for the property 'ProfileImage90'
        }

    }

}
