/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ForemVersionZero.Client.OpenAPIDateConverter;

namespace ForemVersionZero.Model
{
    /// <summary>
    /// Defines ListingCategory
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ListingCategory
    {
        /// <summary>
        /// Enum Cfp for value: cfp
        /// </summary>
        [EnumMember(Value = "cfp")]
        Cfp = 1,

        /// <summary>
        /// Enum Forhire for value: forhire
        /// </summary>
        [EnumMember(Value = "forhire")]
        Forhire = 2,

        /// <summary>
        /// Enum Collabs for value: collabs
        /// </summary>
        [EnumMember(Value = "collabs")]
        Collabs = 3,

        /// <summary>
        /// Enum Education for value: education
        /// </summary>
        [EnumMember(Value = "education")]
        Education = 4,

        /// <summary>
        /// Enum Jobs for value: jobs
        /// </summary>
        [EnumMember(Value = "jobs")]
        Jobs = 5,

        /// <summary>
        /// Enum Mentors for value: mentors
        /// </summary>
        [EnumMember(Value = "mentors")]
        Mentors = 6,

        /// <summary>
        /// Enum Products for value: products
        /// </summary>
        [EnumMember(Value = "products")]
        Products = 7,

        /// <summary>
        /// Enum Mentees for value: mentees
        /// </summary>
        [EnumMember(Value = "mentees")]
        Mentees = 8,

        /// <summary>
        /// Enum Forsale for value: forsale
        /// </summary>
        [EnumMember(Value = "forsale")]
        Forsale = 9,

        /// <summary>
        /// Enum Events for value: events
        /// </summary>
        [EnumMember(Value = "events")]
        Events = 10,

        /// <summary>
        /// Enum Misc for value: misc
        /// </summary>
        [EnumMember(Value = "misc")]
        Misc = 11

    }

}
