/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ForemVersionZero.Client.OpenAPIDateConverter;

namespace ForemVersionZero.Model
{
    /// <summary>
    /// The resource creator
    /// </summary>
    [DataContract(Name = "SharedUser")]
    public partial class SharedUser : IEquatable<SharedUser>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedUser" /> class.
        /// </summary>
        /// <param name="userId">userId.</param>
        /// <param name="name">name.</param>
        /// <param name="username">username.</param>
        /// <param name="twitterUsername">twitterUsername.</param>
        /// <param name="githubUsername">githubUsername.</param>
        /// <param name="websiteUrl">websiteUrl.</param>
        /// <param name="profileImage">Profile image (640x640).</param>
        /// <param name="profileImage90">Profile image (90x90).</param>
        public SharedUser(int userId = default(int), string name = default(string), string username = default(string), string twitterUsername = default(string), string githubUsername = default(string), string websiteUrl = default(string), string profileImage = default(string), string profileImage90 = default(string))
        {
            this.UserId = userId;
            this.Name = name;
            this.Username = username;
            this.TwitterUsername = twitterUsername;
            this.GithubUsername = githubUsername;
            this.WebsiteUrl = websiteUrl;
            this.ProfileImage = profileImage;
            this.ProfileImage90 = profileImage90;
        }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "user_id", EmitDefaultValue = false)]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets TwitterUsername
        /// </summary>
        [DataMember(Name = "twitter_username", EmitDefaultValue = true)]
        public string TwitterUsername { get; set; }

        /// <summary>
        /// Gets or Sets GithubUsername
        /// </summary>
        [DataMember(Name = "github_username", EmitDefaultValue = true)]
        public string GithubUsername { get; set; }

        /// <summary>
        /// Gets or Sets WebsiteUrl
        /// </summary>
        [DataMember(Name = "website_url", EmitDefaultValue = true)]
        public string WebsiteUrl { get; set; }

        /// <summary>
        /// Profile image (640x640)
        /// </summary>
        /// <value>Profile image (640x640)</value>
        [DataMember(Name = "profile_image", EmitDefaultValue = false)]
        public string ProfileImage { get; set; }

        /// <summary>
        /// Profile image (90x90)
        /// </summary>
        /// <value>Profile image (90x90)</value>
        [DataMember(Name = "profile_image_90", EmitDefaultValue = false)]
        public string ProfileImage90 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SharedUser {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  TwitterUsername: ").Append(TwitterUsername).Append("\n");
            sb.Append("  GithubUsername: ").Append(GithubUsername).Append("\n");
            sb.Append("  WebsiteUrl: ").Append(WebsiteUrl).Append("\n");
            sb.Append("  ProfileImage: ").Append(ProfileImage).Append("\n");
            sb.Append("  ProfileImage90: ").Append(ProfileImage90).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SharedUser);
        }

        /// <summary>
        /// Returns true if SharedUser instances are equal
        /// </summary>
        /// <param name="input">Instance of SharedUser to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SharedUser input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.UserId == input.UserId ||
                    this.UserId.Equals(input.UserId)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.TwitterUsername == input.TwitterUsername ||
                    (this.TwitterUsername != null &&
                    this.TwitterUsername.Equals(input.TwitterUsername))
                ) && 
                (
                    this.GithubUsername == input.GithubUsername ||
                    (this.GithubUsername != null &&
                    this.GithubUsername.Equals(input.GithubUsername))
                ) && 
                (
                    this.WebsiteUrl == input.WebsiteUrl ||
                    (this.WebsiteUrl != null &&
                    this.WebsiteUrl.Equals(input.WebsiteUrl))
                ) && 
                (
                    this.ProfileImage == input.ProfileImage ||
                    (this.ProfileImage != null &&
                    this.ProfileImage.Equals(input.ProfileImage))
                ) && 
                (
                    this.ProfileImage90 == input.ProfileImage90 ||
                    (this.ProfileImage90 != null &&
                    this.ProfileImage90.Equals(input.ProfileImage90))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Username != null)
                {
                    hashCode = (hashCode * 59) + this.Username.GetHashCode();
                }
                if (this.TwitterUsername != null)
                {
                    hashCode = (hashCode * 59) + this.TwitterUsername.GetHashCode();
                }
                if (this.GithubUsername != null)
                {
                    hashCode = (hashCode * 59) + this.GithubUsername.GetHashCode();
                }
                if (this.WebsiteUrl != null)
                {
                    hashCode = (hashCode * 59) + this.WebsiteUrl.GetHashCode();
                }
                if (this.ProfileImage != null)
                {
                    hashCode = (hashCode * 59) + this.ProfileImage.GetHashCode();
                }
                if (this.ProfileImage90 != null)
                {
                    hashCode = (hashCode * 59) + this.ProfileImage90.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
