/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ForemVersionZero.Client;
using ForemVersionZero.Api;
// uncomment below to import models
//using ForemVersionZero.Model;

namespace ForemVersionZero.Test.Api
{
    /// <summary>
    ///  Class for testing ArticlesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ArticlesApiTests : IDisposable
    {
        private ArticlesApi instance;

        public ArticlesApiTests()
        {
            instance = new ArticlesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArticlesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ArticlesApi
            //Assert.IsType<ArticlesApi>(instance);
        }

        /// <summary>
        /// Test CreateArticle
        /// </summary>
        [Fact]
        public void CreateArticleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ArticleCreate? articleCreate = null;
            //var response = instance.CreateArticle(articleCreate);
            //Assert.IsType<ArticleShow>(response);
        }

        /// <summary>
        /// Test GetArticleById
        /// </summary>
        [Fact]
        public void GetArticleByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.GetArticleById(id);
            //Assert.IsType<ArticleShow>(response);
        }

        /// <summary>
        /// Test GetArticleByPath
        /// </summary>
        [Fact]
        public void GetArticleByPathTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string slug = null;
            //var response = instance.GetArticleByPath(username, slug);
            //Assert.IsType<ArticleShow>(response);
        }

        /// <summary>
        /// Test GetArticles
        /// </summary>
        [Fact]
        public void GetArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //string? tag = null;
            //string? tags = null;
            //string? tagsExclude = null;
            //string? username = null;
            //string? state = null;
            //int? top = null;
            //int? collectionId = null;
            //var response = instance.GetArticles(page, perPage, tag, tags, tagsExclude, username, state, top, collectionId);
            //Assert.IsType<List<ArticleIndex>>(response);
        }

        /// <summary>
        /// Test GetArticlesWithVideo
        /// </summary>
        [Fact]
        public void GetArticlesWithVideoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetArticlesWithVideo(page, perPage);
            //Assert.IsType<List<ArticleVideo>>(response);
        }

        /// <summary>
        /// Test GetLatestArticles
        /// </summary>
        [Fact]
        public void GetLatestArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetLatestArticles(page, perPage);
            //Assert.IsType<List<ArticleIndex>>(response);
        }

        /// <summary>
        /// Test GetUserAllArticles
        /// </summary>
        [Fact]
        public void GetUserAllArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetUserAllArticles(page, perPage);
            //Assert.IsType<List<ArticleMe>>(response);
        }

        /// <summary>
        /// Test GetUserArticles
        /// </summary>
        [Fact]
        public void GetUserArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetUserArticles(page, perPage);
            //Assert.IsType<List<ArticleMe>>(response);
        }

        /// <summary>
        /// Test GetUserPublishedArticles
        /// </summary>
        [Fact]
        public void GetUserPublishedArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetUserPublishedArticles(page, perPage);
            //Assert.IsType<List<ArticleMe>>(response);
        }

        /// <summary>
        /// Test GetUserUnpublishedArticles
        /// </summary>
        [Fact]
        public void GetUserUnpublishedArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetUserUnpublishedArticles(page, perPage);
            //Assert.IsType<List<ArticleMe>>(response);
        }

        /// <summary>
        /// Test UpdateArticle
        /// </summary>
        [Fact]
        public void UpdateArticleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //ArticleUpdate? articleUpdate = null;
            //var response = instance.UpdateArticle(id, articleUpdate);
            //Assert.IsType<ArticleShow>(response);
        }
    }
}
