/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ForemVersionZero.Client;
using ForemVersionZero.Api;
// uncomment below to import models
//using ForemVersionZero.Model;

namespace ForemVersionZero.Test.Api
{
    /// <summary>
    ///  Class for testing CommentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CommentsApiTests : IDisposable
    {
        private CommentsApi instance;

        public CommentsApiTests()
        {
            instance = new CommentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CommentsApi
            //Assert.IsType<CommentsApi>(instance);
        }

        /// <summary>
        /// Test GetCommentById
        /// </summary>
        [Fact]
        public void GetCommentByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetCommentById(id);
            //Assert.IsType<Comment>(response);
        }

        /// <summary>
        /// Test GetCommentsByArticleId
        /// </summary>
        [Fact]
        public void GetCommentsByArticleIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? aId = null;
            //int? pId = null;
            //var response = instance.GetCommentsByArticleId(aId, pId);
            //Assert.IsType<List<Comment>>(response);
        }
    }
}
