/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ForemVersionZero.Client;
using ForemVersionZero.Api;
// uncomment below to import models
//using ForemVersionZero.Model;

namespace ForemVersionZero.Test.Api
{
    /// <summary>
    ///  Class for testing OrganizationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrganizationsApiTests : IDisposable
    {
        private OrganizationsApi instance;

        public OrganizationsApiTests()
        {
            instance = new OrganizationsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrganizationsApi
            //Assert.IsType<OrganizationsApi>(instance);
        }

        /// <summary>
        /// Test GetOrgArticles
        /// </summary>
        [Fact]
        public void GetOrgArticlesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetOrgArticles(username, page, perPage);
            //Assert.IsType<List<ArticleIndex>>(response);
        }

        /// <summary>
        /// Test GetOrgListings
        /// </summary>
        [Fact]
        public void GetOrgListingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //int? page = null;
            //int? perPage = null;
            //string? category = null;
            //var response = instance.GetOrgListings(username, page, perPage, category);
            //Assert.IsType<List<GetOrgListings200ResponseInner>>(response);
        }

        /// <summary>
        /// Test GetOrgUsers
        /// </summary>
        [Fact]
        public void GetOrgUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetOrgUsers(username, page, perPage);
            //Assert.IsType<List<User>>(response);
        }

        /// <summary>
        /// Test GetOrganization
        /// </summary>
        [Fact]
        public void GetOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.GetOrganization(username);
            //Assert.IsType<Organization>(response);
        }
    }
}
