/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ForemVersionZero.Api;
using ForemVersionZero.Model;
using ForemVersionZero.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ForemVersionZero.Test.Model
{
    /// <summary>
    ///  Class for testing Comment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Comment
        //private Comment instance;

        public CommentTests()
        {
            // TODO uncomment below to create an instance of Comment
            //instance = new Comment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Comment
        /// </summary>
        [Fact]
        public void CommentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Comment
            //Assert.IsType<Comment>(instance);
        }


        /// <summary>
        /// Test the property 'TypeOf'
        /// </summary>
        [Fact]
        public void TypeOfTest()
        {
            // TODO unit test for the property 'TypeOf'
        }
        /// <summary>
        /// Test the property 'IdCode'
        /// </summary>
        [Fact]
        public void IdCodeTest()
        {
            // TODO unit test for the property 'IdCode'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'BodyHtml'
        /// </summary>
        [Fact]
        public void BodyHtmlTest()
        {
            // TODO unit test for the property 'BodyHtml'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

    }

}
