/*
 * DEV API (beta)
 *
 *  Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  All requests must send a user-agent header.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format. 
 *
 * The version of the OpenAPI document: 0.9.7
 * Contact: yo@dev.to
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ForemVersionZero.Api;
using ForemVersionZero.Model;
using ForemVersionZero.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ForemVersionZero.Test.Model
{
    /// <summary>
    ///  Class for testing Organization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganizationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Organization
        //private Organization instance;

        public OrganizationTests()
        {
            // TODO uncomment below to create an instance of Organization
            //instance = new Organization();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Organization
        /// </summary>
        [Fact]
        public void OrganizationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Organization
            //Assert.IsType<Organization>(instance);
        }


        /// <summary>
        /// Test the property 'TypeOf'
        /// </summary>
        [Fact]
        public void TypeOfTest()
        {
            // TODO unit test for the property 'TypeOf'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'TwitterUsername'
        /// </summary>
        [Fact]
        public void TwitterUsernameTest()
        {
            // TODO unit test for the property 'TwitterUsername'
        }
        /// <summary>
        /// Test the property 'GithubUsername'
        /// </summary>
        [Fact]
        public void GithubUsernameTest()
        {
            // TODO unit test for the property 'GithubUsername'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'TechStack'
        /// </summary>
        [Fact]
        public void TechStackTest()
        {
            // TODO unit test for the property 'TechStack'
        }
        /// <summary>
        /// Test the property 'TagLine'
        /// </summary>
        [Fact]
        public void TagLineTest()
        {
            // TODO unit test for the property 'TagLine'
        }
        /// <summary>
        /// Test the property 'Story'
        /// </summary>
        [Fact]
        public void StoryTest()
        {
            // TODO unit test for the property 'Story'
        }
        /// <summary>
        /// Test the property 'JoinedAt'
        /// </summary>
        [Fact]
        public void JoinedAtTest()
        {
            // TODO unit test for the property 'JoinedAt'
        }
        /// <summary>
        /// Test the property 'ProfileImage'
        /// </summary>
        [Fact]
        public void ProfileImageTest()
        {
            // TODO unit test for the property 'ProfileImage'
        }

    }

}
